### ISSUE TITLE
Loosing pagehide on mobile browsers 

### ISSUE THREAD

**Issue by NejcZdovc** [blotoutio/sdk-js#8]
![image](https://user-images.githubusercontent.com/9574457/111426207-98e1a900-86f4-11eb-9c22-99d6f66dca16.png)

**Comment by pawan-blotout** [comment]
pagehide is not reliable, especially on mobile. For example, the pagehide event is not fired at all in the following scenario:

A mobile user visits your page.
The user then switches to a different app.
Later, the user closes the browser from the app manager.

Instead we can use visibilitychange. and where visibilitychange is not supported pagehide is next-best alternative

**Comment by NejcZdovc** [comment]
based on findings this will be implemented in https://github.com/blotoutio/sdk-js/issues/13
